name: fluwe
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # 图像压缩
  flutter_image_compress: ^0.6.5+1

  # 网络图片缓存
  cached_network_image: ^2.0.0

  # 图片选择器
  image_picker: ^0.6.3

  # 分享
  share: ^0.6.3+5

  # 本地缓存
  shared_preferences: ^0.5.6

  # 软件、页面启动器
  url_launcher: ^5.4.1

  # 获取包信息
  package_info: ^0.4.0+13

  # 设备信息
  device_info: ^0.4.1+4

  # 设备唯一标识（针对ios的唯一标识）
  # unique_ids: ^1.0.10

  # 视频播放器
  # video_player: ^0.10.5+1
  
  # 网页
  # webview_flutter: ^0.3.19+4
  # 下载（苹果不行）
  # flutter_downloader: ^1.4.0

  # 原生toast
  fluttertoast: ^3.1.3
  #请求库
  dio: ^3.0.8

  #权限
  permission_handler: ^4.1.0

  # 微信库
  # fluwx: ^1.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
